Support export/import states with arbitrary players.
Card-Forge/forge pull request #2168
Opened 2022-12-26 03:47 UTC by asvitkine

Previously, the dump/setup game state dev options were only able to handle a 2-player human vs. AI game. This PR expands the functionality to support any number of players and ignores the type of player (naming them p0,p1,...,pN). The previous names of ai and human are supported for backwards compatibility.

2022-12-26 04:28 UTC, kevlahnota commented
Didn't test but IIRC the puzzle uses gamestate too, does it work?

2022-12-26 06:14 UTC, asvitkine commented
> Didn't test but IIRC the puzzle uses gamestate too, does it work with the existing puzzle mode?

Yes it does. :)

2022-12-26 10:18 UTC, tool4ever requested changes
Attachments broken:
> ERROR: Tried to create a non-existent card named Curse of BloodlettingP1 (set: any) when loading game state!

2022-12-26 12:22 UTC, tool4ever commented on forge-ai/src/main/java/forge/ai/GameState.java
> +        for (int i = 0; i < playerStates.size(); i++) {
Just use for-each here and following further below?

2022-12-27 04:35 UTC, asvitkine commented
> Attachments broken:
> 
> > ERROR: Tried to create a non-existent card named Curse of BloodlettingP1 (set: any) when loading game state!

Thanks, fixed! A line of code was accidentally removed that caused this. Should be good now.

2022-12-28 04:17 UTC, asvitkine commented
On Mon, Dec 26, 2022 at 5:22 AM tool4ever ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In forge-ai/src/main/java/forge/ai/GameState.java
> <https://github.com/Card-Forge/forge/pull/2168#discussion_r1057218259>:
>
> > @@ -712,10 +621,11 @@ protected void applyGameOnThread(final Game game) {
>
>          // Set negative or zero life after state effects if need be, important for some puzzles that rely on
>          // pre-setting negative life (e.g. PS_NEO4).
> -        if (humanLife <= 0) {
> -            human.setLife(humanLife, null);
> -        } else if (computerLife <= 0) {
> -            ai.setLife(computerLife, null);
> +        for (int i = 0; i < playerStates.size(); i++) {
>
> Just use for-each here and following further below?
>
We index into two different player lists, so can't.


> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Card-Forge/forge/pull/2168#pullrequestreview-1230065581>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAEJ4CFTZRVOEHDFRXYPVDWPGE2BANCNFSM6AAAAAATJKVLPQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-28 14:50 UTC, tool4ever approved these changes
nice work

2022-12-28 14:56 UTC, merged