add ManaCostShard Map and cleanup Desktop
Card-Forge/forge pull request #5215
Opened 2024-05-08 05:19 UTC by Hanmac

Closes #5207 

First Step in cleaning up the code

This Part is for Desktop

For Mobile, the problem is the extra Enum FSkinImage in between, i need to think about that can be removed/refactored too

2024-05-17 05:15 UTC, Agetian commented
Looks good so far! :)

2024-05-17 20:13 UTC, tool4ever commented on forge-gui-desktop/src/main/java/forge/toolbox/FSkin.java
> +        addEncodingSymbol("P", FSkinProp.IMG_MANA_PHRYX);}
why is this called 20 times too?

2024-05-17 20:26 UTC, tool4ever requested changes
I tried to select _Ayara, Widow of the Realm_ in deck editor:
```
EDT > java.lang.NullPointerException: Cannot invoke "forge.toolbox.FSkin$SkinImage.resize(int, int)" because the return value of "java.util.Map.get(Object)" is null
	at forge.toolbox.CardFaceSymbols.drawSymbol(CardFaceSymbols.java:274)
	at forge.toolbox.imaging.FCardImageRenderer$SymbolPiece.drawCurrent(FCardImageRenderer.java:977)
	at forge.toolbox.imaging.FCardImageRenderer$Paragraph.drawPieces(FCardImageRenderer.java:1086)
	at forge.toolbox.imaging.FCardImageRenderer.drawTextBoxText(FCardImageRenderer.java:1156)
	at forge.toolbox.imaging.FCardImageRenderer.drawTextBox(FCardImageRenderer.java:822)
	at forge.toolbox.imaging.FCardImageRenderer.drawCardStateImage(FCardImageRenderer.java:425)
	at forge.toolbox.imaging.FCardImageRenderer.drawCardImage(FCardImageRenderer.java:279)
	at forge.ImageCache.getOriginalImageInternal(ImageCache.java:310)
	at forge.ImageCache.getOriginalImage(ImageCache.java:158)
	at forge.toolbox.imaging.FImageUtil.getImage(FImageUtil.java:59)
	at forge.gui.CardPicturePanel.getImage(CardPicturePanel.java:136)
	at forge.gui.CardPicturePanel.setImage(CardPicturePanel.java:92)
	at forge.gui.CardPicturePanel.setCard(CardPicturePanel.java:85)
	at forge.screens.match.controllers.CPicture.showCard(CPicture.java:75)
	at forge.screens.match.controllers.CDetailPicture.update(CDetailPicture.java:97)
	at forge.screens.match.controllers.CDetailPicture.showCard(CDetailPicture.java:52)
	at forge.screens.match.controllers.CDetailPicture.showItem(CDetailPicture.java:72)
	at forge.screens.deckeditor.CDeckEditorUI.setCard(CDeckEditorUI.java:100)
	at forge.screens.deckeditor.CDeckEditorUI$7.valueChanged(CDeckEditorUI.java:279)
	at forge.itemmanager.views.ItemView.onSelectionChange(ItemView.java:311)
	at forge.itemmanager.views.ItemListView$ItemTableModel$2.focusGained(ItemListView.java:611)
```

2024-05-18 10:07 UTC, tool4ever approved these changes

2024-05-18 10:13 UTC, merged