ETB update: Java code: `Card.java`, `CardFactoryUtil.java`
Card-Forge/forge pull request #5839
Opened 2024-08-04 14:52 UTC by dracontes

Split off from https://github.com/Card-Forge/forge/pull/5720

2024-08-04 15:31 UTC, Hanmac commented on forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
> +        if (keyword.equals("CARDNAME enters tapped.")) {
This Section can be removed, because "K:CARDNAME enters tapped." doesn't exist anymore?

2024-08-04 19:12 UTC, tool4ever approved these changes

2024-08-04 19:47 UTC, Hanmac reviewed
Just a Blocker so it doesn't get merged yet

2024-08-04 19:48 UTC, Hanmac requested changes
Just a Blocker so it doesn't get merged yet

2024-08-05 05:06 UTC, Hanmac approved these changes

2024-08-05 05:06 UTC, merged